In [1]:










import numpy as np

from sklearn.model_selection import StratifiedKFold
import numpy
# fix random seed for reproducibility




import math



from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

from sklearn.impute import SimpleImputer
from pprint import pprint


#import pandas as pd
from sklearn.preprocessing import MinMaxScaler
#from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier
#from sklearn.cross_validation import train_test_split 
import numpy as np 


# roc curve and auc score
from sklearn.datasets import make_classification
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
#import Tkinter as tk





from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report
#from sklearn.grid_search import GridSearchCV

import numpy as np 
#import matplotlib.pyplot as plt 






import pandas as pd
#data=pd.read_csv("prebp40.csv",delimiter=";" ,decimal="."),sep='\t'
data=pd.read_csv("cust_seg1.csv"  )


#from sklearn.model_selection import train_test_split




 
data=data.replace('NA',np.nan)
data=data.replace(' ',0)



# data['Baseline_previousseasoninjury']=data['Baseline_previousseasoninjury'].replace('OUI, mais participation complète à l entrainement ou en compétition, malgré une blessure/problème physique',	1)
# data['Baseline_previousseasoninjury']=data['Baseline_previousseasoninjury'].replace('OUI, mais participation réduite à l entrainement ou en compétition, à ...',	1)















In [2]:
# Looking at the code above, it is appropriate to remove all trailing spaces from the "age" and "antiguedad" columns. There is a method named strip to do this

data["age"] = data["age"].apply(lambda string: string.strip())
data["antiguedad"] = data["antiguedad"].apply(lambda string: string.strip())



In [3]:
# The "age" and "antiguedad" columns are encoded as strings, not numbers

def convert_to_int(data):
    try:
        return int(data)
    except:
        return data

data["age"] = data["age"].apply(convert_to_int)
data["antiguedad"] = data["antiguedad"].apply(convert_to_int)
















In [4]:
# Convert "NA" strings into the Pandas nan type

data["age"] = data["age"].replace("NA", np.nan)
data["antiguedad"] = data["antiguedad"].replace("NA", np.nan)

In [5]:
# How many NA are in each column?
for col in data:
    print(col + ":", data[col].isna().sum())

Unnamed: 0: 0
fecha_dato: 0
ncodpers: 0
ind_empleado: 1
pais_residencia: 1
sexo: 1
age: 1
fecha_alta: 1
ind_nuevo: 1
antiguedad: 1
indrel: 1
ult_fec_cli_1t: 575
indrel_1mes: 1
tiprel_1mes: 1
indresi: 1
indext: 1
conyuemp: 576
canal_entrada: 1
indfall: 1
tipodom: 1
cod_prov: 1
nomprov: 1
ind_actividad_cliente: 1
renta: 105


In [6]:


X1=[data['age'],data["antiguedad"]]




#imp = IterativeImputer(max_iter=10, random_state=0)
from sklearn.impute import KNNImputer
imp = KNNImputer(n_neighbors=2, weights="uniform")
imp.fit(X1)
SimpleImputer()
# X = [[np.nan, 2], [6, np.nan], [7, 6]]
print(imp.transform(X1))
 #imp.fit(Y)
 #SimpleImputer()
# X = [[np.nan, 2], [6, np.nan], [7, 6]]






###### one way to remove n

imp = IterativeImputer(max_iter=10, random_state=0)

imp.fit(X1)
SimpleImputer()
# X = [[np.nan, 2], [6, np.nan], [7, 6]]
print(imp.transform(X1))
 #imp.fit(Y)
 #SimpleImputer()
# X = [[np.nan, 2], [6, np.nan], [7, 6]]










[[35. 23. 23. ... 23. 23. 24.]
 [ 6. 35. 35. ... 35. 35. 35.]]
[[35. 23. 23. ... 23. 23. 24.]
 [ 6. 35. 35. ... 35. 35. 35.]]
